# coding: utf-8

"""
    Doofinder API v2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@doofinder.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pydoof
from pydoof.models.update_data_type import UpdateDataType  # noqa: E501
from pydoof.rest import ApiException


class TestUpdateDataType(unittest.TestCase):
    """UpdateDataType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateDataType(self):
        """Test UpdateDataType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pydoof.models.update_data_type.UpdateDataType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
