# coding: utf-8

"""
    Doofinder API v2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@doofinder.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pydoof2
from pydoof2.api.temp_indices_api import TempIndicesApi  # noqa: E501
from pydoof2.rest import ApiException


class TestTempIndicesApi(unittest.TestCase):
    """TempIndicesApi unit test stubs"""

    def setUp(self):
        self.api = pydoof2.api.temp_indices_api.TempIndicesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_reindex_to_temp(self):
        """Test case for reindex_to_temp

        Reindex the content of the real index into the temporary one.  # noqa: E501
        """
        pass

    def test_replace_by_temp(self):
        """Test case for replace_by_temp

        Replace the real index with the temporary one.  # noqa: E501
        """
        pass

    def test_temporary_index_create(self):
        """Test case for temporary_index_create

        Creates a temporary index  # noqa: E501
        """
        pass

    def test_temporary_index_delete(self):
        """Test case for temporary_index_delete

        Deletes the temporary index.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
