# coding: utf-8

"""
    Doofinder API v2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@doofinder.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pydoof
from pydoof.api.stats_api import StatsApi  # noqa: E501
from pydoof.rest import ApiException


class TestStatsApi(unittest.TestCase):
    """StatsApi unit test stubs"""

    def setUp(self):
        self.api = pydoof.api.stats_api.StatsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_banners_clicks(self):
        """Test case for banners_clicks

        Get the total amount of clicks banners have got  # noqa: E501
        """
        pass

    def test_banners_display(self):
        """Test case for banners_display

        Get the total amount of displays banners have got  # noqa: E501
        """
        pass

    def test_checkouts(self):
        """Test case for checkouts

        Get total checkouts  # noqa: E501
        """
        pass

    def test_checkouts_by_date(self):
        """Test case for checkouts_by_date

        Get the checkouts by dates  # noqa: E501
        """
        pass

    def test_clicks(self):
        """Test case for clicks

        Get total clicks  # noqa: E501
        """
        pass

    def test_clicks_by_date(self):
        """Test case for clicks_by_date

        Get the clicks by dates  # noqa: E501
        """
        pass

    def test_clicks_by_query(self):
        """Test case for clicks_by_query

        Get the products clicked given a certain query  # noqa: E501
        """
        pass

    def test_clicks_top(self):
        """Test case for clicks_top

        Get the most common clicks  # noqa: E501
        """
        pass

    def test_inits(self):
        """Test case for inits

        Get total sessions started  # noqa: E501
        """
        pass

    def test_inits_by_date(self):
        """Test case for inits_by_date

        Get the sessions started by dates  # noqa: E501
        """
        pass

    def test_metrics(self):
        """Test case for metrics

        Get the search engines usage.  # noqa: E501
        """
        pass

    def test_redirects(self):
        """Test case for redirects

        Get the total amount of redirects done  # noqa: E501
        """
        pass

    def test_searches(self):
        """Test case for searches

        Get total searches  # noqa: E501
        """
        pass

    def test_searches_by_click(self):
        """Test case for searches_by_click

        Get the top searches that got a product clicked  # noqa: E501
        """
        pass

    def test_searches_by_date(self):
        """Test case for searches_by_date

        Get the searches by dates  # noqa: E501
        """
        pass

    def test_searches_top(self):
        """Test case for searches_top

        Get the most common searches  # noqa: E501
        """
        pass

    def test_usage(self):
        """Test case for usage

        Get the search engines usage.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
