# coding: utf-8

"""
    Doofinder API v2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@doofinder.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pydoof2
from pydoof2.api.proxy_api import ProxyApi  # noqa: E501
from pydoof2.rest import ApiException


class TestProxyApi(unittest.TestCase):
    """ProxyApi unit test stubs"""

    def setUp(self):
        self.api = pydoof2.api.proxy_api.ProxyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_logs(self):
        """Test case for logs

        List tasks logs  # noqa: E501
        """
        pass

    def test_task_details(self):
        """Test case for task_details

        Get Task details  # noqa: E501
        """
        pass

    def test_tasks_process(self):
        """Test case for tasks_process

        Process Search Engine Data Sources  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
