# coding: utf-8

"""
    Doofinder API v2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@doofinder.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pydoof
from pydoof.api.search_engines_api import SearchEnginesApi  # noqa: E501
from pydoof.rest import ApiException


class TestSearchEnginesApi(unittest.TestCase):
    """SearchEnginesApi unit test stubs"""

    def setUp(self):
        self.api = pydoof.api.search_engines_api.SearchEnginesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_search_engine_create(self):
        """Test case for search_engine_create

        Create new search engine   # noqa: E501
        """
        pass

    def test_search_engine_delete(self):
        """Test case for search_engine_delete

        Delete a search engine  # noqa: E501
        """
        pass

    def test_search_engine_list(self):
        """Test case for search_engine_list

        List search engines  # noqa: E501
        """
        pass

    def test_search_engine_show(self):
        """Test case for search_engine_show

        Get a search engine  # noqa: E501
        """
        pass

    def test_search_engine_update(self):
        """Test case for search_engine_update

        Update a search engine  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
