# coding: utf-8

"""
    Doofinder API v2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@doofinder.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pydoof2
from pydoof2.api.tasks_api import TasksApi  # noqa: E501
from pydoof2.rest import ApiException


class TestTasksApi(unittest.TestCase):
    """TasksApi unit test stubs"""

    def setUp(self):
        self.api = pydoof2.api.tasks_api.TasksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_process(self):
        """Test case for process

        Process Search Engine Data Sources  # noqa: E501
        """
        pass

    def test_process_status(self):
        """Test case for process_status

          # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
