# coding: utf-8

"""
    Doofinder API v2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@doofinder.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pydoof
from pydoof.api.health_api import HealthApi  # noqa: E501
from pydoof.rest import ApiException


class TestHealthApi(unittest.TestCase):
    """HealthApi unit test stubs"""

    def setUp(self):
        self.api = pydoof.api.health_api.HealthApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_status(self):
        """Test case for status

        Load balancer check  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
