[tool.ruff]
line-length = 119
indent-width = 4
target-version = "py38"

[tool.ruff.lint]
extend-select = [
  "UP",  # pyupgrade
  "I",  # isort rules
  "E", # pyflakes
  "TRY",
]

[tool.ruff.lint.pyupgrade]
# Keep compatibility with Python 3.8
keep-runtime-typing = true
