# coding: utf-8

"""
    Doofinder API v2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@doofinder.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from pydoof2.models.data_types import DataTypes  # noqa: F401,E501
from pydoof2.models.new_search_engine import NewSearchEngine  # noqa: F401,E501


class SearchEngine(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'stopwords': 'bool',
        'site_url': 'str',
        'name': 'str',
        'language': 'str',
        'inactive': 'bool',
        'hashid': 'str',
        'datatypes': 'DataTypes'
    }

    attribute_map = {
        'stopwords': 'stopwords',
        'site_url': 'site_url',
        'name': 'name',
        'language': 'language',
        'inactive': 'inactive',
        'hashid': 'hashid',
        'datatypes': 'datatypes'
    }

    def __init__(self, stopwords=None, site_url=None, name=None, language=None, inactive=None, hashid=None, datatypes=None):  # noqa: E501
        """SearchEngine - a model defined in Swagger"""  # noqa: E501

        self._stopwords = None
        self._site_url = None
        self._name = None
        self._language = None
        self._inactive = None
        self._hashid = None
        self._datatypes = None
        self.discriminator = None

        if stopwords is not None:
            self.stopwords = stopwords
        if site_url is not None:
            self.site_url = site_url
        self.name = name
        self.language = language
        if inactive is not None:
            self.inactive = inactive
        if hashid is not None:
            self.hashid = hashid
        if datatypes is not None:
            self.datatypes = datatypes

    @property
    def stopwords(self):
        """Gets the stopwords of this SearchEngine.  # noqa: E501

        Ignore high-frequency terms like \"the\", \"and\", \"is\". These words have a low weight and contribute little to the relevance score.  # noqa: E501

        :return: The stopwords of this SearchEngine.  # noqa: E501
        :rtype: bool
        """
        return self._stopwords

    @stopwords.setter
    def stopwords(self, stopwords):
        """Sets the stopwords of this SearchEngine.

        Ignore high-frequency terms like \"the\", \"and\", \"is\". These words have a low weight and contribute little to the relevance score.  # noqa: E501

        :param stopwords: The stopwords of this SearchEngine.  # noqa: E501
        :type: bool
        """

        self._stopwords = stopwords

    @property
    def site_url(self):
        """Gets the site_url of this SearchEngine.  # noqa: E501

        The url of the site for the search engine  # noqa: E501

        :return: The site_url of this SearchEngine.  # noqa: E501
        :rtype: str
        """
        return self._site_url

    @site_url.setter
    def site_url(self, site_url):
        """Sets the site_url of this SearchEngine.

        The url of the site for the search engine  # noqa: E501

        :param site_url: The site_url of this SearchEngine.  # noqa: E501
        :type: str
        """

        self._site_url = site_url

    @property
    def name(self):
        """Gets the name of this SearchEngine.  # noqa: E501

        A verbose name that helps to describe the search engine  # noqa: E501

        :return: The name of this SearchEngine.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SearchEngine.

        A verbose name that helps to describe the search engine  # noqa: E501

        :param name: The name of this SearchEngine.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def language(self):
        """Gets the language of this SearchEngine.  # noqa: E501

        An ISO 639-1 language code that determines the language of the search engine. E.g.: ‘es’.  # noqa: E501

        :return: The language of this SearchEngine.  # noqa: E501
        :rtype: str
        """
        return self._language

    @language.setter
    def language(self, language):
        """Sets the language of this SearchEngine.

        An ISO 639-1 language code that determines the language of the search engine. E.g.: ‘es’.  # noqa: E501

        :param language: The language of this SearchEngine.  # noqa: E501
        :type: str
        """
        if language is None:
            raise ValueError("Invalid value for `language`, must not be `None`")  # noqa: E501

        self._language = language

    @property
    def inactive(self):
        """Gets the inactive of this SearchEngine.  # noqa: E501

        Indicates if the search engine has been deactivated and therefore it can not receive requests (read-only)  # noqa: E501

        :return: The inactive of this SearchEngine.  # noqa: E501
        :rtype: bool
        """
        return self._inactive

    @inactive.setter
    def inactive(self, inactive):
        """Sets the inactive of this SearchEngine.

        Indicates if the search engine has been deactivated and therefore it can not receive requests (read-only)  # noqa: E501

        :param inactive: The inactive of this SearchEngine.  # noqa: E501
        :type: bool
        """

        self._inactive = inactive

    @property
    def hashid(self):
        """Gets the hashid of this SearchEngine.  # noqa: E501

        A unique code that identify a search engine (read-only)  # noqa: E501

        :return: The hashid of this SearchEngine.  # noqa: E501
        :rtype: str
        """
        return self._hashid

    @hashid.setter
    def hashid(self, hashid):
        """Sets the hashid of this SearchEngine.

        A unique code that identify a search engine (read-only)  # noqa: E501

        :param hashid: The hashid of this SearchEngine.  # noqa: E501
        :type: str
        """

        self._hashid = hashid

    @property
    def datatypes(self):
        """Gets the datatypes of this SearchEngine.  # noqa: E501

        List of datatypes  # noqa: E501

        :return: The datatypes of this SearchEngine.  # noqa: E501
        :rtype: DataTypes
        """
        return self._datatypes

    @datatypes.setter
    def datatypes(self, datatypes):
        """Sets the datatypes of this SearchEngine.

        List of datatypes  # noqa: E501

        :param datatypes: The datatypes of this SearchEngine.  # noqa: E501
        :type: DataTypes
        """

        self._datatypes = datatypes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SearchEngine, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SearchEngine):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
