# coding: utf-8

"""
    Doofinder API v2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@doofinder.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from pydoof2.api_client import ApiClient


class SearchEnginesApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def search_engine_create(self, searchengine, **kwargs):  # noqa: E501
        """Create new search engine   # noqa: E501

        Create a new search engine  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.search_engine_create(searchengine, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param NewSearchEngine searchengine: Search engine data (required)
        :return: SearchEngine
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.search_engine_create_with_http_info(searchengine, **kwargs)  # noqa: E501
        else:
            (data) = self.search_engine_create_with_http_info(searchengine, **kwargs)  # noqa: E501
            return data

    def search_engine_create_with_http_info(self, searchengine, **kwargs):  # noqa: E501
        """Create new search engine   # noqa: E501

        Create a new search engine  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.search_engine_create_with_http_info(searchengine, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param NewSearchEngine searchengine: Search engine data (required)
        :return: SearchEngine
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['searchengine']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method search_engine_create" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'searchengine' is set
        if ('searchengine' not in params or
                params['searchengine'] is None):
            raise ValueError("Missing the required parameter `searchengine` when calling `search_engine_create`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'searchengine' in params:
            body_params = params['searchengine']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_token', 'jwt_token']  # noqa: E501

        return self.api_client.call_api(
            '/api/v2/search_engines', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SearchEngine',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def search_engine_delete(self, hashid, **kwargs):  # noqa: E501
        """Delete a search engine  # noqa: E501

        Delete a search engine  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.search_engine_delete(hashid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str hashid: Search engine identifier (hashid) (required)
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.search_engine_delete_with_http_info(hashid, **kwargs)  # noqa: E501
        else:
            (data) = self.search_engine_delete_with_http_info(hashid, **kwargs)  # noqa: E501
            return data

    def search_engine_delete_with_http_info(self, hashid, **kwargs):  # noqa: E501
        """Delete a search engine  # noqa: E501

        Delete a search engine  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.search_engine_delete_with_http_info(hashid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str hashid: Search engine identifier (hashid) (required)
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['hashid']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method search_engine_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'hashid' is set
        if ('hashid' not in params or
                params['hashid'] is None):
            raise ValueError("Missing the required parameter `hashid` when calling `search_engine_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'hashid' in params:
            path_params['hashid'] = params['hashid']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_token', 'jwt_token']  # noqa: E501

        return self.api_client.call_api(
            '/api/v2/search_engines/{hashid}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='object',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def search_engine_list(self, **kwargs):  # noqa: E501
        """List search engines  # noqa: E501

        List search engines  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.search_engine_list(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: SearchEngines
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.search_engine_list_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.search_engine_list_with_http_info(**kwargs)  # noqa: E501
            return data

    def search_engine_list_with_http_info(self, **kwargs):  # noqa: E501
        """List search engines  # noqa: E501

        List search engines  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.search_engine_list_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: SearchEngines
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method search_engine_list" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_token', 'jwt_token']  # noqa: E501

        return self.api_client.call_api(
            '/api/v2/search_engines', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SearchEngines',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def search_engine_show(self, hashid, **kwargs):  # noqa: E501
        """Get a search engine  # noqa: E501

        Get a search engine given by his hashid  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.search_engine_show(hashid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str hashid: Search engine identifier (hashid) (required)
        :return: SearchEngine
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.search_engine_show_with_http_info(hashid, **kwargs)  # noqa: E501
        else:
            (data) = self.search_engine_show_with_http_info(hashid, **kwargs)  # noqa: E501
            return data

    def search_engine_show_with_http_info(self, hashid, **kwargs):  # noqa: E501
        """Get a search engine  # noqa: E501

        Get a search engine given by his hashid  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.search_engine_show_with_http_info(hashid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str hashid: Search engine identifier (hashid) (required)
        :return: SearchEngine
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['hashid']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method search_engine_show" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'hashid' is set
        if ('hashid' not in params or
                params['hashid'] is None):
            raise ValueError("Missing the required parameter `hashid` when calling `search_engine_show`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'hashid' in params:
            path_params['hashid'] = params['hashid']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_token', 'jwt_token']  # noqa: E501

        return self.api_client.call_api(
            '/api/v2/search_engines/{hashid}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SearchEngine',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def search_engine_update(self, hashid, searchengine, **kwargs):  # noqa: E501
        """Update a search engine  # noqa: E501

        Update a search engine by the given hashid  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.search_engine_update(hashid, searchengine, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str hashid: Search engine identifier (hashid) (required)
        :param NewSearchEngine searchengine: Search engine data (required)
        :return: SearchEngine
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.search_engine_update_with_http_info(hashid, searchengine, **kwargs)  # noqa: E501
        else:
            (data) = self.search_engine_update_with_http_info(hashid, searchengine, **kwargs)  # noqa: E501
            return data

    def search_engine_update_with_http_info(self, hashid, searchengine, **kwargs):  # noqa: E501
        """Update a search engine  # noqa: E501

        Update a search engine by the given hashid  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.search_engine_update_with_http_info(hashid, searchengine, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str hashid: Search engine identifier (hashid) (required)
        :param NewSearchEngine searchengine: Search engine data (required)
        :return: SearchEngine
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['hashid', 'searchengine']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method search_engine_update" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'hashid' is set
        if ('hashid' not in params or
                params['hashid'] is None):
            raise ValueError("Missing the required parameter `hashid` when calling `search_engine_update`")  # noqa: E501
        # verify the required parameter 'searchengine' is set
        if ('searchengine' not in params or
                params['searchengine'] is None):
            raise ValueError("Missing the required parameter `searchengine` when calling `search_engine_update`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'hashid' in params:
            path_params['hashid'] = params['hashid']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'searchengine' in params:
            body_params = params['searchengine']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_token', 'jwt_token']  # noqa: E501

        return self.api_client.call_api(
            '/api/v2/search_engines/{hashid}', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SearchEngine',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
